### ISSUE TITLE
startup/config file

### ISSUE THREAD

**Issue by irmen** [irmen/cx16shell#13]
Recently a couple of  changes were made to the shell to prepare for user-customizing it. 
In #9 a bunch of questions were raised concerning a way to have a startup and/or config file for the shell.

Let's discuss this topic here.

> 1. are we going to continue using _modt.txt_ for now, or we'll implement _shell.rc_ from the beginning?

_motd.txt_ shall remain purely a text file.

We shall have a second file that will contain the commands to run at startup. Call it _shell.rc_ or _init.sh_ or something like that.  I guess the rc one is closer to the name of similar files used by other shells (bashrc and such)

> 2. are we going to work from my current commits or should we start form scratch again?

I'm guessing start over? There wasn't much here atm and it was going the route of modifying motd.txt, what I don't like.

> 3. if we implement _shell.rc_, should we make a separate folder for config files maybe, or are we going to place everything into `SHELL-CMDS` as it is now? (i think we will need to make subfolders of `SHELL-CMDS` sooner or later - I already had an idea of a `lib` folder while back ago for hypothetical more complex command-line software, that'd need external libraries)

I don't know about this. I don't see a benefit yet to make more subdirectories. There's not much in shell-cmds right now so it's not cluttered at all as it is

> 4. are we going to allow everything or maybe only selected commands for safety (I guess the answer's everything, based on what you said)
> 5. If we go _shell.rc_ route, should it be just for executing commands on boot or should it also be a config file? If so, how are we going to differentiate between a config option and a command?

Yeah I think we should keep it simple, just interpret every line as a command to execute (+ its arguments). A while ago I added a few configuration commands to the shell to set the screen mode and colors, so those can be in the file just as well.
The last command in the file could be `cat  //shell-cmds/:motd.txt` to get the shell to write the motd text file if you so desire. So no more special logic in the shell itself is needed to print this file.

I guess we need a way to add a comment line as well. Maybe if it starts with '#' . Or implement a 'rem' command (naaah).

> 6. If _shell.rc_ route, what if user doesn't have the _shell.rc_? Will `SHELL.PRG` create a default config, crash, or run some kind of default routine completely ambiguous to end user?

Just start the shell as it starts now?  It's not a failure condition to have no config file.  It could create a new (empty?) one if none exists (with a comment in it to tell its purpose?) but that's a nice to have

> 7. Multiple commands in shell.rc? (probably yes)
> 8. is Motd on boot going to be configured in _shell.rc_ or will it run regardless of what _shell.rc_ says?

I think these have been addressed above!

**Comment by adiee5** [comment]
Nice! I will answer when I get back home

**Comment by adiee5** [comment]
Ok, i'm back. Firstly, I think some of the questions have answered themself with the time, for example question 5, where the path we are going with became obvious when you added `color` and `mode` commands. And yeah, question 2 also became irrelevant as the branch just was becoming more and more outdated.

> > 3. if we implement shell.rc, should we make a separate folder for config files maybe, or are we going to place everything into SHELL-CMDS as it is now? (i think we will need to make subfolders of SHELL-CMDS sooner or later - I already had an idea of a lib folder while back ago for hypothetical more complex command-line software, that'd need external libraries)

> I don't know about this. I don't see a benefit yet to make more sub-directories. There's not much in shell-cmds right now so it's not cluttered at all as it is

I think of it as a future proofing. Sooner or later, there probably will be some commands, that would need some static external files to work. Idk, maybe sth dependent on ZSMkit (although ZSMkit is expected to be embedded in the executable itself, so maybe not the best example), or some command that require some static image files, that can't be just stuffed into the executable (especially since the max size of exe is more or less cut in half here). If oodler decides to port the vim to work as an external command, we'll have to give him some kind of way to import the VTUI, as his project relies on it (unless he's no longer using it, idk). Additionally, I really don't think it's a good idea to mix config data with executables, it can get messy really quickly. So yeah, i think it'd be a good idea if we add 2 predefined folders: `/SHELL-CMDS/CFG/` for configuration files (currently `motd.txt` and `shell.rc` or whatever we'll call it) and a second folder, which we can call either `/SHELL-CMDS/LIB/` or `/SHELL-CMDS/DATA/` for static Files (libraries and some non-executable data too), that commands depend on. It's up to debate which one we'll choose, but i think `DATA` might be better, as libraries are not the only thing, that's going to be stored there. 

As a side note, I have been developing a new command for a while now - a `man` command, for displaying some kind of documentation about shell and commands. At this point I'd say it's 80% done and it definitely needs to have some predefined place for all of the documentation files. But that's a talk for another thread. let's get back to the config thing.

> I guess we need a way to add a comment line as well. Maybe if it starts with '#' . Or implement a 'rem' command (naaah).

Yeah, I also was thinking about it. and I wasn't sure if we should go the POSIX way - `#` or the 6502 way - `;`. `rem` is a no go.

> Just start the shell as it starts now? It's not a failure condition to have no config file. It could create a new (empty?) one if none exists (with a comment in it to tell its purpose?) but that's a nice to have

Yeah, sounds reasonable

> >8. is Motd on boot going to be configured in shell.rc or will it run regardless of what shell.rc says?

> I think these have been addressed above!

So, if i understand correctly, none of the regular startup routines (or at least none that are required in order to make shell work) should be executed when config file is present.

**Comment by irmen** [comment]
> wasn't sure if we should go the POSIX way
we can do both, but that might just be confusing.  In the context of a shell, let's just settle on '#'.

> regular startup routines
what routines do you mean? There's only the hardcoded motd check and that one will be removed

**Comment by adiee5** [comment]
> what routines do you mean? There's only the hardcoded motd check and that one will be removed

hmm, yeah you're right

> let's just settle on '#'.

ok

**Comment by irmen** [comment]
So the config file support is in.

But maybe a few questions remain:

- command to run a script.   Separate command? Or just extend the 'run' command or builtin support for ".sh" files?
- directories for the files. It's all stuffed into SHELL-CMDS now which is okay for me until now. Maybe wait till your man pages support is almost done?  I wonder where you put those?

**Comment by adiee5** [comment]
> command to run a script. Separate command? Or just extend the 'run' command or builtin support for ".sh" files?

i was thinking about maybe `sh` but idk. Since SHELL.PRG by design likes to do implied commands (`<folder>` instead of `cd <folder>`, `<prgname>` instead of `run <prgname>` etc.) i think we could also make the shell check if first 4 bytes of the file are `#!sh` or `#!SH`, and execute the file as a script in this case.

> Maybe wait till your man pages support is almost done? I wonder where you put those?

currently, it looks for manpages in `/manpages`, but this was never intended to be the final destination. The code is currently flexible enough to have the path changed at any moment. I thought about `/SHELL-CMDS/DATA/man/` as a destination for all man pages, but i'm waiting for your opinion.

**Comment by irmen** [comment]
If the man-pages are intended for the shell only, they should be inside a folder related to the shell.
Which brings us to perhaps renaming SHELL-CMDS and reorganizing after all. What about

SHELL-FILES/
  |
  +-- commands/     (all external commands and shell scripts go here)
  +-- manpages/      (your man pages go inside here)
  +-- config.sh          just lives in the shell files folder itself?  Not in the commands folder, it's not a script you should be able to run ad-hoc. or should you?

**Comment by adiee5** [comment]
Oh, ok, so man gets a special treatment i see? I'm happy with that. I doubt any ext-cmd relies on its own location on a disk anyway. My don't at least

**Comment by irmen** [comment]
it's not forbidden to add stuff into the shell folder I guess :)

**Comment by adiee5** [comment]
>+-- commands/ (all external commands **_and shell scripts_** go here)

wait a minute, one can shove shell scripts to commans folder? 🤨

**Comment by adiee5** [comment]
> it's not forbidden to add stuff into the shell folder I guess :) Just thinking about keeping stuff related to the shell inside 1 main folder in the root at least

yeah, this is how it should be

**Comment by irmen** [comment]
> > +-- commands/ (all external commands **_and shell scripts_** go here)
> 
> wait a minute, one can shove shell scripts to commans folder? 🤨

objections?  They're also stuff you can "run".

**Comment by adiee5** [comment]
i mean, yeah, but i mean, is SHELL physically capable of distinguishing between ext-cmds and scripts inside the `/shell-files/commands`?

**Comment by irmen** [comment]
if it ends with .sh it treats it as a script.

**Comment by irmen** [comment]
This is pretty much all implemented now
